-- Generated by db/extract-seed.py from the HTML pages. Do not edit by hand.
-- Regenerate with: python db/extract-seed.py

DELETE FROM services;
DELETE FROM gallery;
DELETE FROM testimonials;
DELETE FROM settings;

-- Services (14 domestic, 2 commercial)
INSERT INTO services (category, title, description, image_key, image_alt, featured, sort_order) VALUES ('domestic', 'Fitted Kitchens', 'Kitchens built and fitted around how you cook, with clever storage and a finish that lasts.', '/Media/fitted-kitchen.jpg', 'Fitted shaker kitchen in deep navy with oak flooring and white worktops', 1, 1);
INSERT INTO services (category, title, description, image_key, image_alt, featured, sort_order) VALUES ('domestic', 'Fitted Bathrooms', 'Complete bathroom fitting, from vanity units to bath panels, measured tight and finished clean.', '/Media/fitted-bathroom.jpg', 'Fitted bathroom with walnut vanity unit, oak flooring and tiled shower', 0, 2);
INSERT INTO services (category, title, description, image_key, image_alt, featured, sort_order) VALUES ('domestic', 'Fitted Wardrobes', 'Floor-to-ceiling wardrobes designed around your room, including sloped ceilings and awkward corners, with interiors laid out your way.', '/Media/fitted-wardrobe.jpg', 'Floor-to-ceiling fitted wardrobes', 1, 3);
INSERT INTO services (category, title, description, image_key, image_alt, featured, sort_order) VALUES ('domestic', 'Fitted Furniture', 'Alcove units, bookcases, media walls and shelving made to measure. Clean lines, clever storage and a seamless built-in finish.', '/Media/fitted-furniture.jpg', 'Fitted alcove cabinets and floating shelves', 0, 4);
INSERT INTO services (category, title, description, image_key, image_alt, featured, sort_order) VALUES ('domestic', 'Fitted Windows', 'Windows supplied and fitted square, sealed and draught free, finished neatly inside and out.', '/Media/fitted-windows.jpg', 'White framed windows newly fitted in a brick wall', 0, 5);
INSERT INTO services (category, title, description, image_key, image_alt, featured, sort_order) VALUES ('domestic', 'Doors', 'Internal and external doors supplied, hung and finished, including frames, architraves, locks and hardware fitted with precision.', '/Media/door.jpg', 'Internal timber door hung and finished', 1, 6);
INSERT INTO services (category, title, description, image_key, image_alt, featured, sort_order) VALUES ('domestic', 'Flooring', 'Solid and engineered wood flooring laid flat, level and lasting, with skirting and trims to match.', '/Media/flooring.jpg', 'Engineered oak flooring laid through a bright bay-windowed room', 0, 7);
INSERT INTO services (category, title, description, image_key, image_alt, featured, sort_order) VALUES ('domestic', 'Wall Panelling', 'Classic and contemporary panelling in shaker, slatted and traditional styles that bring warmth and character to any room.', '/Media/panelling.jpg', 'Wall panelling installation', 0, 8);
INSERT INTO services (category, title, description, image_key, image_alt, featured, sort_order) VALUES ('domestic', 'Wooden Partitioning', 'Timber stud walls and partitions that reshape your space, built solid, insulated and ready for plastering.', '/Media/wooden-partitioning.jpg', 'Timber stud wall partition with insulation, mid build', 0, 9);
INSERT INTO services (category, title, description, image_key, image_alt, featured, sort_order) VALUES ('domestic', 'Cladding', 'Exterior timber cladding that transforms the look of your home, fitted straight and sealed against the weather.', '/Media/cladding.jpg', 'Cedar clad home extension with grey framed glazing', 0, 10);
INSERT INTO services (category, title, description, image_key, image_alt, featured, sort_order) VALUES ('domestic', 'Garden Decking', 'Beautiful, hard-wearing decks that extend your living space outdoors, built on solid foundations to weather the seasons.', '/Media/decking.jpg', 'Garden decking with timber balustrade', 1, 11);
INSERT INTO services (category, title, description, image_key, image_alt, featured, sort_order) VALUES ('domestic', 'Fencing & Gates', 'Sturdy, straight and properly set fencing and gates. Privacy, security and kerb appeal in one job done right.', '/Media/fence.jpg', 'Timber garden fencing', 0, 12);
INSERT INTO services (category, title, description, image_key, image_alt, featured, sort_order) VALUES ('domestic', 'Garden Rooms', 'Garden rooms built from the ground up: insulated, clad and glazed for year-round use as an office, gym or retreat.', '/Media/garden-room.jpg', 'Cedar clad garden room with sliding glass doors and a small deck', 0, 13);
INSERT INTO services (category, title, description, image_key, image_alt, featured, sort_order) VALUES ('domestic', 'Soffits, Fascias & Guttering', 'Soffits, fascias and guttering replaced and installed properly, keeping your roofline tidy and weathertight.', '/Media/soffits-fascias-guttering.jpg', 'New white soffits and fascias with black guttering on a tiled roofline', 0, 14);
INSERT INTO services (category, title, description, image_key, image_alt, featured, sort_order) VALUES ('commercial', 'Fire Doors', 'Certified fire doors supplied and fitted to regulation, with closers, seals and hardware done right for offices, communal areas and commercial premises.', '/Media/fire-door.jpg', 'Certified oak fire door fitted with overhead closer and intumescent seals', 0, 1);
INSERT INTO services (category, title, description, image_key, image_alt, featured, sort_order) VALUES ('commercial', 'Metal Partitioning', 'Metal stud partitioning for offices and commercial units, built straight, insulated and ready for boarding.', '/Media/metal-partitioning.jpg', 'Metal stud partitioning with insulation in a commercial unit, mid fit-out', 0, 2);

-- Gallery (16 photos)
INSERT INTO gallery (caption, image_key, image_alt, sort_order) VALUES ('Fitted Kitchen', '/Media/fitted-kitchen.jpg', 'Fitted shaker kitchen in deep navy with oak flooring', 1);
INSERT INTO gallery (caption, image_key, image_alt, sort_order) VALUES ('Fitted Bathroom', '/Media/fitted-bathroom.jpg', 'Fitted bathroom with walnut vanity unit and oak flooring', 2);
INSERT INTO gallery (caption, image_key, image_alt, sort_order) VALUES ('Fitted Wardrobes', '/Media/fitted-wardrobe.jpg', 'Floor-to-ceiling fitted wardrobes', 3);
INSERT INTO gallery (caption, image_key, image_alt, sort_order) VALUES ('Fitted Alcove Furniture', '/Media/fitted-furniture.jpg', 'Fitted oak alcove cabinets and floating shelves', 4);
INSERT INTO gallery (caption, image_key, image_alt, sort_order) VALUES ('Fitted Windows', '/Media/fitted-windows.jpg', 'White framed windows newly fitted in a brick wall', 5);
INSERT INTO gallery (caption, image_key, image_alt, sort_order) VALUES ('Doors & Finish Carpentry', '/Media/door.jpg', 'Internal timber door hung and finished', 6);
INSERT INTO gallery (caption, image_key, image_alt, sort_order) VALUES ('Wood Flooring', '/Media/flooring.jpg', 'Engineered oak flooring laid through a bright bay-windowed room', 7);
INSERT INTO gallery (caption, image_key, image_alt, sort_order) VALUES ('Wall Panelling', '/Media/panelling.jpg', 'Precisely fitted wall panelling', 8);
INSERT INTO gallery (caption, image_key, image_alt, sort_order) VALUES ('Wooden Partitioning', '/Media/wooden-partitioning.jpg', 'Timber stud wall partition with insulation, mid build', 9);
INSERT INTO gallery (caption, image_key, image_alt, sort_order) VALUES ('Timber Cladding', '/Media/cladding.jpg', 'Cedar clad home extension with grey framed glazing', 10);
INSERT INTO gallery (caption, image_key, image_alt, sort_order) VALUES ('Garden Room', '/Media/garden-room.jpg', 'Cedar clad garden room with sliding glass doors and a small deck', 11);
INSERT INTO gallery (caption, image_key, image_alt, sort_order) VALUES ('Garden Decking', '/Media/decking.jpg', 'Timber garden decking with balustrade', 12);
INSERT INTO gallery (caption, image_key, image_alt, sort_order) VALUES ('Fencing & Gates', '/Media/fence.jpg', 'Timber garden fencing', 13);
INSERT INTO gallery (caption, image_key, image_alt, sort_order) VALUES ('Soffits, Fascias & Guttering', '/Media/soffits-fascias-guttering.jpg', 'New white soffits and fascias with black guttering', 14);
INSERT INTO gallery (caption, image_key, image_alt, sort_order) VALUES ('Fire Doors', '/Media/fire-door.jpg', 'Certified oak fire door with overhead closer and intumescent seals', 15);
INSERT INTO gallery (caption, image_key, image_alt, sort_order) VALUES ('Metal Partitioning', '/Media/metal-partitioning.jpg', 'Metal stud partitioning in a commercial unit, mid fit-out', 16);

-- Contact settings
INSERT INTO settings (key, value) VALUES ('areas_commercial', 'Commercial work across Sussex, Kent and London');
INSERT INTO settings (key, value) VALUES ('areas_domestic', 'Domestic work across Sussex and Kent');
INSERT INTO settings (key, value) VALUES ('email', 'stuart@shawscarpentry.com');
INSERT INTO settings (key, value) VALUES ('form_endpoint', 'https://formspree.io/f/xpqvkpjl');
INSERT INTO settings (key, value) VALUES ('hours_weekday', 'Monday to Friday, 8am to 6pm');
INSERT INTO settings (key, value) VALUES ('hours_weekend', 'Saturday by appointment');
INSERT INTO settings (key, value) VALUES ('phone_display', '+44 7477 392931');
INSERT INTO settings (key, value) VALUES ('phone_href', '+447477392931');

-- No testimonials yet: the home page keeps showing the
-- "Reviews coming soon" card until the first one is published.
